# Secret example
# To activate run: `kubectl apply -f mongodb-secret.yaml`
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-username: bW9uZ28=
  mongo-password: MTIzNA==
